# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.12-slim

# avoid prompts
ENV DEBIAN_FRONTEND=noninteractive
# ensure stdout/stderr unbuffered
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# copy project files
COPY pyproject.toml requirements.txt ./
COPY scenext_mcp ./scenext_mcp
COPY mcp_config.json ./

# install dependencies and package
RUN pip install --no-cache-dir . \
    && rm -rf /root/.cache/pip

# default command (can be overridden by MCP runtime)
CMD ["scenext-mcp", "stdio"]
