name: 发布到 PyPI

on:
  push:
    tags:
      - 'v*'  # 当推送 v* 标签时触发，如 v1.0.0
  release:
    types: [published]  # 当创建 GitHub Release 时触发

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 安装构建依赖
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: 安装项目依赖
      run: |
        pip install -r requirements.txt
        
    - name: 运行测试（可选）
      run: |
        # 这里可以添加测试命令，例如：
        # python -m pytest tests/
        echo "暂时跳过测试..."
        
    - name: 构建包
      run: |
        python -m build
        
    - name: 验证包
      run: |
        twine check dist/*
        
    - name: 发布到 PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
